---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    JOBS: 1
    secure: fOTO/HpUT0xsfml9iXuEL9qBu0NVErcig6CmrS1DFv7f4x9/mYQMNzLUv5b6VBPqGHeFNHiGaUUza3Ufc5KpL7DOu/1y6TFQlSoM6MRRdIXb+50MObvkJ4wXwYJH7Zrb4g8RTaBOY9uU5XQkm/E6GWWF3NiYFoVzCYPNSgAALko1caoEX2hoJNXJSd0T4G+gxtxc2g08RGunBPLqIyy2avMRN4yq0WDN2NbBrztM01FA5RoOLPyX0hhzyIZ+45z34wKvZtu7rj9h1KbFOZOVFJWpHDa0bXxhF63ldxPINe2QMOSsOD22Czk1+IKyC+88gtkvUq7pGUaJK6YdVDRcW9G/DMHVy/IE2aFabrPDVgzrmeCoVKzATzt8nMfIMTTu9Unoa5fdohpJ0NPhYnPfVAGfJ+2MPITgP+x2X6M5+KgHCBdaIgwBVnZE9DTb1L9c/Eh50zeHHbfv9L+NVlbQFzMWNj+kKWMj0qwh6JPpSFiKaOvTK6XP+NSUc7euAZgqK6lwqS07pvcql4qvzbeRWyn/GZuRHOGvfkUNuvLee8dMKfpF3s1VQ6blHHqKB8qH2ifxawiztWgUkYxK0GFTk//ZopLzP90bLl0JiGlg517tp5V9eBOK5ZlPwsSOhD+wta9gCssPjK4i2H2IwLox7AqXegigBMdqIbXz9LaFVAY=

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/
    # greenkeeper branches
    - /^greenkeeper\/.*$/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - COVERAGE=true yarn test
        - codecov

    # - name: "Floating Dependencies"
    #   script:
    #     - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    rooms:
      secure: JxzpZkdYQWVuREscnT2Xw0v7JkkrbifgyrjaTG3dGaaq4eSoLZngEGYfxnms6QLwdzMovizjIH500BuYMCcCd2e0jQSu6X5iMM9S+J9xDtJPvHImOcNhvbp3iDK7YNMmxfjGYcB3XDt6mCHzLtGzslUuh56Vhlpq+4WcDfPLKFVLc2AiTTAq79I8M1bXPkNv0afQ7S0k8zKCl1o6rDHuvA7/3AxwRmb1iAok3uCvMUynRyWtgg07d6x9b2vJr17kKigWOfIPRWNbVYgLy918P/e/Jr/leCYKsb7Ze1aGAqrxw3jkQ6qYCtB4ud4XJxQuqprlDjCAins17ZnoicFkOWGEHeeXRyTQbX1D1s71DJrjcLYRvhwX46k5TmnVu/YR2P5EgKplVp7bHulyNxa0WqvNoNMm/Cu7/qmjVEGP2ZpTUJTfQt1GFT2GBYUeza9Pc8fxKMXR3468UA5duzgXjdhxjFUp8+qgPquFG2xri4FBCCg217XXYEwDsoAN2F0RAVSUqkYY4Q+jijjNj5ahawyD2UBaMbohbZMvriM64NyJYoasaAjkEM1Fvo4/F7N8rvtfYn9163W7xSAC4vQG4tFTxa48xKgdKErv8BGijXJzXu7J9AZYin81QWbrFSwBofdqAkOanuoDOrJ38rlb4sAdEikrpYFFyMydWA8GDPU=

deploy:
  provider: npm
  skip_cleanup: true
  email: devo.tox.89@gmail.com
  api_key:
    secure: mLKnhNd27pXata5UfKOIS8l8dh8WoferEY+XpvTqKlnbHevOeH01IRlfICykG/lZUHnMW7rjjY0OX4ZTaDcpwMb+ZqRM2LCO7Uh6f74guL4Lv+ryjg4xhzbWn9r2ANIy1vZbFqtMalLE89DyQhscTMx2lVm9NNMMQd7K13ygvOwlrlR98aHpC276AH8r1EBWbIpX2PsgqW/ZJ+m5wYghS/WS0wMOx/zTav2e2uPJEma/nboZYdB11/YmEkJFtB/nqHYAd3wDdu/aXnDzrpEbY8aRJLONdeZwy4KflHhAZgswBgsBI70H8thfTHahKQGknzTJTfNmuGxx+gZ8Ihzsx4VGPlFoFtAFtC++oUbzRlyhx5vzXzWey5C+dEnCLfO9TiKndrR84lvkyI7D6Bp9EMC/8jsYJymzuvnNpphd6PByXfUszeWBWb7c4yb0S9SCnwWDMXwaBu9fg5mu0wODXNub5Wxgdhw/gEiZPCfIAzlrBYTnlZjyZsC1OkndLoPajnA+L25x4sjH5Dx9FPjd4YhAM1/3TQiw2+70r4aUuk7GLeMBxEpcmz+AJVdxU7zYQ8YAjObxOOKHWX2Y00PPErT6wRYaIF5WuJSLHs57rkci6vpDK+pQJjhhzVIKYZgGicCO5S5+e37bR35tkrsswA5Dqdp/iy3CddFP2w49AuE=
  on:
    tags: true
    repo: devotox/ember-paper-pikaday
